--------------------------------------------------------
--  PSSUS SQL
--------------------------------------------------------

--------------------------------------------------------
--  DDL for Table USTUser
--------------------------------------------------------

CREATE TABLE "SLLIAC"."USTUSER"
(	"ID" NUMBER(19,0),
     "EMAIL" VARCHAR2(255 BYTE),
     "PASSWORD" VARCHAR2(2000 BYTE),
     "FIRSTNAME" VARCHAR2(255 BYTE),
     "LASTNAME" VARCHAR2(255 BYTE),
     "STUDENTID" VARCHAR2(20 BYTE),
     "PHONE" VARCHAR2(20 BYTE),
     "STUDYYEAR" VARCHAR2(20 BYTE),
     "WALLETID" VARCHAR2(20 BYTE),
     "PROGRAM" VARCHAR2(20 BYTE),
     "RIGHT" VARCHAR2(20 BYTE)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ISOM3260"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Index USER_PK
--------------------------------------------------------

CREATE UNIQUE INDEX "SLLIAC"."USER_PK" ON "SLLIAC"."USTUSER" ("ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ISOM3260" ;
--------------------------------------------------------
--  Constraints for Table USTUser
--------------------------------------------------------

ALTER TABLE "SLLIAC"."USTUSER" MODIFY ("EMAIL" NOT NULL ENABLE);
ALTER TABLE "SLLIAC"."USTUSER" MODIFY ("PASSWORD" NOT NULL ENABLE);
ALTER TABLE "SLLIAC"."USTUSER" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
ALTER TABLE "SLLIAC"."USTUSER" MODIFY ("LASTNAME" NOT NULL ENABLE);
ALTER TABLE "SLLIAC"."USTUSER" ADD CONSTRAINT "USER_PK" PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ISOM3260"  ENABLE;


CREATE TABLE LCSD_SOCCER_PITCH_SCHEDULE (
    ID INTEGER,
    DISTRICT_NAME_EN VARCHAR2(255 BYTE),
    DISTRICT_NAME_TC NVARCHAR2(255),
    VENUE_NAME_EN VARCHAR2(255 BYTE),
    VENUE_NAME_TC NVARCHAR2(255),
    VENUE_ADDRESS_EN VARCHAR2(255 BYTE),
    VENUE_ADDRESS_TC NVARCHAR2(255),
    VENUE_PHONE_NO VARCHAR2(20 BYTE),
    VENUE_LONGITUDE VARCHAR2(20 BYTE),
    VENUE_LATITUDE VARCHAR2(20 BYTE),
    FACILITY_TYPE_NAME_EN VARCHAR2(255 BYTE),
    FACILITY_TYPE_NAME_TC VARCHAR2(255 BYTE),
    FACILITY_LOCATION_NAME_EN VARCHAR2(255 BYTE),
    FACILITY_LOCATION_NAME_TC VARCHAR2(255 BYTE),
    AVAILABLE_DATE VARCHAR2(20 BYTE),
    SESSION_START_TIME VARCHAR2(20 BYTE),
    SESSION_END_TIME VARCHAR2(20 BYTE),
    AVAILABLE_COURTS INTEGER,
    STATUS_CODE VARCHAR2(20 BYTE),
    PRIMARY KEY (ID)
    );

CREATE SEQUENCE schedule_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


CREATE TABLE Soccer_Pitch_Type (
                               ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               PitchType VARCHAR2(50),
                               Description VARCHAR2(50),
                               Price NUMBER
);
INSERT INTO Soccer_Pitch_Type (PitchType, Description, Price) VALUES ('Soccer Pitch', 'Grass', 1000);
INSERT INTO Soccer_Pitch_Type (PitchType, Description, Price) VALUES ('Min. Soccer Pitch', 'Grass', 800);
INSERT INTO Soccer_Pitch_Type (PitchType, Description, Price) VALUES ('Soccer Pitch', 'Art. Turf', 1200);
INSERT INTO Soccer_Pitch_Type (PitchType, Description, Price) VALUES ('Min. Soccer Pitch', 'Art. Turf', 900);

CREATE TABLE LCSD_DISTRICT (
                               district_id NUMBER PRIMARY KEY,
                               district_name_en VARCHAR2(100) NOT NULL,
                               district_name_tc VARCHAR2(100) NOT NULL,
                               district_shortform VARCHAR2(20) NOT NULL
);
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (1, 'Central & Western', '中西區', 'C&W');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (2, 'Kwai Tsing', '葵青區', 'KT');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (3, 'Islands', '離島區', 'Islands');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (4, 'Sham Shui Po', '深水埗區', 'SSP');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (5, 'Eastern', '東區', 'Eastern');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (6, 'Tuen Mun', '屯門區', 'TM');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (7, 'Wan Chai', '灣仔區', 'WC');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (8, 'Yau Tsim Mong', '油尖旺區', 'YTM');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (9, 'Tai Po', '大埔區', 'TP');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (10, 'Sha Tin', '沙田區', 'ST');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (11, 'Kowloon City', '九龍城區', 'KC');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (12, 'Tsuen Wan', '荃灣區', 'TW');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (13, 'North', '北區', 'North');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (14, 'Yuen Long', '元朗區', 'YL');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (15, 'Kwun Tong', '觀塘區', 'KT');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (16, 'Wong Tai Sin', '黃大仙區', 'WTS');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (17, 'Southern', '南區', 'South');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (18, 'Sai Kung', '西貢區', 'SK');

CREATE TABLE PSSUS_Booking_Record (
                                      booking_Id INT NOT NULL,
                                      student_Id VARCHAR(255) NOT NULL,
                                      campaign_Detail VARCHAR(255),
                                      campaign_remark VARCHAR(255),
                                      join_person VARCHAR(255),
                                      email VARCHAR(255),
                                      phone VARCHAR(20),
                                      personal_trainer VARCHAR(255),
                                      schedule_id INT,
                                      PRIMARY KEY (booking_Id),
                                      FOREIGN KEY (schedule_id) REFERENCES LCSD_SOCCER_PITCH_SCHEDULE(id)
);

CREATE SEQUENCE booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE booking_txn_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE booking_join_seq
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE wallet_id_seq
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE uststd_seq
    START WITH 500
    INCREMENT BY 1;