--------------------------------------------------------
--  File created - Wednesday-September-11-2024
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USTSTUDENT
--------------------------------------------------------

CREATE TABLE "USTSTUDENT"
(	"ID" NUMBER(19,0),
     "EMAIL" VARCHAR2(255 BYTE),
     "PASSWORD" VARCHAR2(2000 BYTE),
     "FIRSTNAME" VARCHAR2(255 BYTE),
     "LASTNAME" VARCHAR2(255 BYTE)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
REM INSERTING into ISOM5260.USTSTUDENT
SET DEFINE OFF;
Insert into USTSTUDENT (ID,EMAIL,PASSWORD,FIRSTNAME,LASTNAME) values (41,'teas121@gmail.com','$2a$10$W6orrnjpSosU3bijKG1kjOlGb8D72PyJTEpnhE2QRMUe5L68t/nhS','get','er');
Insert into USTSTUDENT (ID,EMAIL,PASSWORD,FIRSTNAME,LASTNAME) values (1,'sd@gmail.com','$2a$10$axCtIfUFNm4cneDfcAto3eL2M.FkswoV9jAWUAGOLvSWRAjcCgBZi','12','12');
Insert into USTSTUDENT (ID,EMAIL,PASSWORD,FIRSTNAME,LASTNAME) values (2,'test@test.com','$2a$10$jLu8BXDocTUVzu67VTCZt.20uTdM/MYHPx4Ki8WEdoNDyqAT5fQs6','1a','1a');
Insert into USTSTUDENT (ID,EMAIL,PASSWORD,FIRSTNAME,LASTNAME) values (23,'test1@test.com','$2a$10$muAAp2m3v9sxP3H9g4KvSuwvaQVfeFSM0dNgES/DA91abC/vFpQTO','test','test');
Insert into USTSTUDENT (ID,EMAIL,PASSWORD,FIRSTNAME,LASTNAME) values (43,'test@test2.com','$2a$10$Ue0PI89B5ITG8mQTf35x9Ogvk3vSBZVGn.CNu6WoMzr0i8Pqab8I.','1a','1a');
Insert into USTSTUDENT (ID,EMAIL,PASSWORD,FIRSTNAME,LASTNAME) values (42,'test@test.com111','$2a$10$JY6rJ8VXj70pVrNm9bKHCuLmnUV2eKRNVIN5yCvl4psECMBK5OV5G','11','1');
--------------------------------------------------------
--  DDL for Index USER_PK
--------------------------------------------------------

CREATE UNIQUE INDEX "USER_PK" ON "USTSTUDENT" ("ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--------------------------------------------------------
--  Constraints for Table USTSTUDENT
--------------------------------------------------------

ALTER TABLE "USTSTUDENT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "USTSTUDENT" MODIFY ("EMAIL" NOT NULL ENABLE);
ALTER TABLE "USTSTUDENT" MODIFY ("PASSWORD" NOT NULL ENABLE);
ALTER TABLE "USTSTUDENT" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
ALTER TABLE "USTSTUDENT" MODIFY ("LASTNAME" NOT NULL ENABLE);
ALTER TABLE "USTSTUDENT" ADD CONSTRAINT "USER_PK" PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);



CREATE TABLE LCSD_SOCCER_PITCH_SCHEDULE (
    ID INTEGER,
    DISTRICT_NAME_EN VARCHAR2(255 BYTE),
    DISTRICT_NAME_TC NVARCHAR2(255),
    VENUE_NAME_EN VARCHAR2(255 BYTE),
    VENUE_NAME_TC NVARCHAR2(255),
    VENUE_ADDRESS_EN VARCHAR2(255 BYTE),
    VENUE_ADDRESS_TC NVARCHAR2(255),
    VENUE_PHONE_NO VARCHAR2(20 BYTE),
    VENUE_LONGITUDE VARCHAR2(20 BYTE),
    VENUE_LATITUDE VARCHAR2(20 BYTE),
    FACILITY_TYPE_NAME_EN VARCHAR2(255 BYTE),
    FACILITY_TYPE_NAME_TC VARCHAR2(255 BYTE),
    FACILITY_LOCATION_NAME_EN VARCHAR2(255 BYTE),
    FACILITY_LOCATION_NAME_TC VARCHAR2(255 BYTE),
    AVAILABLE_DATE VARCHAR2(20 BYTE),
    SESSION_START_TIME VARCHAR2(20 BYTE),
    SESSION_END_TIME VARCHAR2(20 BYTE),
    AVAILABLE_COURTS INTEGER,
    PRIMARY KEY (ID , SESSION_START_TIME, FACILITY_LOCATION_NAME_EN, SESSION_END_TIME)
    );

CREATE SEQUENCE schedule_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


CREATE TABLE Soccer_Pitch_Type (
                               ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               PitchType VARCHAR2(50),
                               Description VARCHAR2(50),
                               Price NUMBER
);
INSERT INTO Soccer_Pitch_Type (PitchType, Description, Price) VALUES ('Soccer Pitch', 'Grass', 1000);
INSERT INTO Soccer_Pitch_Type (PitchType, Description, Price) VALUES ('Min. Soccer Pitch', 'Grass', 800);
INSERT INTO Soccer_Pitch_Type (PitchType, Description, Price) VALUES ('Soccer Pitch', 'Art. Turf', 1200);
INSERT INTO Soccer_Pitch_Type (PitchType, Description, Price) VALUES ('Min. Soccer Pitch', 'Art. Turf', 900);

CREATE TABLE LCSD_DISTRICT (
                               district_id NUMBER PRIMARY KEY,
                               district_name_en VARCHAR2(100) NOT NULL,
                               district_name_tc VARCHAR2(100) NOT NULL,
                               district_shortform VARCHAR2(20) NOT NULL
);
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (1, 'Central & Western', '中西區', 'C&W');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (2, 'Kwai Tsing', '葵青區', 'KT');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (3, 'Islands', '離島區', 'Islands');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (4, 'Sham Shui Po', '深水埗區', 'SSP');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (5, 'Eastern', '東區', 'Eastern');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (6, 'Tuen Mun', '屯門區', 'TM');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (7, 'Wan Chai', '灣仔區', 'WC');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (8, 'Yau Tsim Mong', '油尖旺區', 'YTM');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (9, 'Tai Po', '大埔區', 'TP');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (10, 'Sha Tin', '沙田區', 'ST');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (11, 'Kowloon City', '九龍城區', 'KC');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (12, 'Tsuen Wan', '荃灣區', 'TW');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (13, 'North', '北區', 'North');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (14, 'Yuen Long', '元朗區', 'YL');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (15, 'Kwun Tong', '觀塘區', 'KT');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (16, 'Wong Tai Sin', '黃大仙區', 'WTS');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (17, 'Southern', '南區', 'South');
INSERT INTO LCSD_DISTRICT (district_id, district_name_en, district_name_tc, district_shortform) VALUES (18, 'Sai Kung', '西貢區', 'SK');



