flowchart TD
    A[Create Student Account] --> B[Award 3000 Credit Points]
    B --> C{Campaign Options}
    C -->|Initiate Own Campaign| D[Enter Campaign Details]
    C -->|Participate in Existing Campaign| E[Join Campaign]
    D --> F[Set Campaign as Pending Approval]

    A1[Search Panel for Create Campaign] --> G[Search by District] --> DDD[Return List of Avaliable Schedule]
    A1 --> H[Search by Time] --> DDD[Return List of Avaliable Schedule]
    A1 --> ZZZ[Search by Place] --> DDD[Return List of Avaliable Schedule]

    A2[Backend: SyncLCSDSoccerPitchJob] --> I[Run every 5 minutes]
    I --> J[Sync from LCSD & Compare with LCSD_SOCCER_PITCH_SCHEDULE]
    J --> K{Record Found?}
    K -->|No| L[Create New Entry]
    K -->|Yes| M[Update Availability Status]
    I --> N[Housekeeping Outdated Records]
    N --> O[Set Status to TIME_SLOT_STARTED in Schedule]
    O --> P[Mark Unapproved Bookings as NOT_APPROVED_AND_TIME_SLOT_STARTED]

    A4[Admin Approval] --> Q[Approve/Decline Booking Requests]
    Q --> R{Request Status}
    R -->|Rejected| S[Change Status to RECORD_REJECTED]
    R -->|Approved| T[Deduct Points from Host]
    T --> U[Update Booking Status to RECORD_APPROVED]
    U --> V[Participants can Attend Event]

    A5[JasperReport] --> W[Monthly Statement for Members]
    A5 --> Y[Detailed Reports for Administrators]

    A6[Backend: DailyPointRewardJob] --> Z[Run Daily at 12:00]
    Z --> AA[Credit 20 Points to Members with Student Rights]